const DOCS = 'https://hermes-agent.nousresearch.com/docs/';

export type CuratedAnswer = {
  question: string;
  answer: string;
  /** Link on the "Nous documentation" source line and the "Learn more" button. */
  learn: string;
  learnLabel?: string;
  /** Primary button. */
  cta: string;
  url: string;
};

/**
 * The curated questions shown in the ⌘K palette. The palette shows them three at a time in the order of
 * `QUESTION_ORDER` (two pages), and each has a backdrop in public/assets/nous-web/composer/composer-<art>.webp.
 * These are fixed copy, not generated by an AI.
 */
export const answers: CuratedAnswer[] = [
  {
    question: 'See what you can build with Hermes?',
    answer:
      'Turn repeat work into an agent workflow: research a topic, prepare a briefing, schedule reports, or connect tools you already use. Hermes supports reusable skills, memory, and scheduled tasks. Start with one useful job and expand from there.',
    learn: DOCS,
    cta: 'Explore releases',
    url: '/releases',
  },
  {
    question: 'How do I get Hermes?',
    answer:
      'Install Hermes, connect a model provider, and give it a first task. The desktop installer is the simplest starting point on macOS or Windows; the installation guide covers command-line setup and Linux. You choose which tools and services to connect.',
    learn: `${DOCS}getting-started/installation`,
    cta: 'Download Hermes',
    url: 'https://hermes-agent.nousresearch.com/',
  },
  {
    question: 'What makes Nous different?',
    answer:
      'Nous builds open language models and the infrastructure for distributed training. Its stated mission connects open access to AI with human rights and freedoms, with research spanning model architecture, data synthesis, fine-tuning, and reasoning.',
    learn: '/',
    cta: 'Explore releases',
    url: '/releases',
  },
  {
    question: 'Which model should I use?',
    answer:
      'Start with your task, available hardware, and whether you want local or hosted inference. Hermes Agent supports multiple providers and models; it is not tied to a single Hermes model. Compare capability, speed, and cost before committing to a setup.',
    learn: `${DOCS}user-guide/configuration`,
    cta: 'Compare models',
    url: '/releases',
  },
  {
    question: 'Can I run this privately?',
    answer:
      'You can run Hermes on your own machine, but local execution is not a guarantee that data stays there. Cloud model requests and connected tools can send data to external services. Review your provider, permissions, and tool configuration before using sensitive information.',
    learn: `${DOCS}user-guide/security`,
    cta: 'Review config',
    url: `${DOCS}user-guide/configuration`,
  },
  {
    question: 'How can I contribute?',
    answer:
      'Help improve Hermes through code, documentation, bug reports, or testing. Read the contribution guide to find the right workflow, or join the community to discuss an idea. If you want to work with Nous full-time, explore the open roles.',
    learn: '/careers',
    learnLabel: 'Open roles',
    cta: 'Join the community',
    url: 'https://discord.gg/nousresearch',
  },
];

/** Backdrop picture for each answer (same index as `answers`). */
export const ANSWER_ART = ['build', 'install', 'nous', 'models', 'private', 'contribute'] as const;

/** Order the questions appear in: indexes into `answers`, three per page. */
export const QUESTION_ORDER = [2, 0, 1, 3, 4, 5] as const;
export const QUESTIONS_PER_PAGE = 3;
export const QUESTION_PAGES = 2;
