export type Release = {
  /** MM/DD/YY, shown as written. */
  date: string;
  /** Category tag: MODEL, PAPER, DATASET, ... */
  type: string;
  /** Optional size column (omit to show an em dash). */
  size?: string;
  title: string;
  href: string;
  description: string;
};

/** Newest first. The page shows the first 9 and reveals the rest with "Show more". */
export const releases: Release[] = [
  {
    date: '02/25/26',
    type: 'AGENT',
    title: 'Hermes Agent',
    href: 'https://hermes-agent.nousresearch.com/',
    description:
      'An autonomous agent that lives on your server, remembers what it learns, and gets more capable the longer it runs.',
  },
  {
    date: '01/06/26',
    type: 'MODEL',
    title: 'NousCoder-14B',
    href: 'https://huggingface.co/NousResearch/NousCoder-14B',
    description: 'Competitive olympiad programming post-trained on Qwen-3-14B',
  },
  {
    date: '12/09/25',
    type: 'MODEL',
    title: 'Nomos 1',
    href: 'https://huggingface.co/NousResearch/nomos-1',
    description: 'Small but mighty 30B SOTA mathematician in partnership with Hillclimb',
  },
  {
    date: '12/03/25',
    type: 'MODEL',
    title: 'Hermes-4.3-Seed-36B',
    href: 'https://huggingface.co/NousResearch/Hermes-4.3-36B',
    description:
      'Roughly equivalent performance to Hermes-4-70B at half the model size; post-trained entirely on the Psyche network',
  },
  {
    date: '08/26/25',
    type: 'PAPER',
    title: 'Hermes 4 Technical Report',
    href: '/wp-content/uploads/2025/08/Hermes_4_Technical_Report.pdf',
    description: 'Technical Report',
  },
  {
    date: '08/26/25',
    type: 'MODEL',
    title: 'Hermes‑4‑Llama‑3.1‑405B',
    href: 'https://huggingface.co/collections/NousResearch/hermes-4-collection-68a731bfd452e20816725728',
    description: 'Frontier hybrid‑mode reasoning model based on Llama‑3.1‑405B',
  },
  {
    date: '08/26/25',
    type: 'MODEL',
    title: 'Hermes‑4‑Llama‑3.1‑70B',
    href: 'https://huggingface.co/collections/NousResearch/hermes-4-collection-68a731bfd452e20816725728',
    description:
      'Smaller hybrid‑mode reasoning model with 70B parameters. Shares the same improvements as the 405B variant',
  },
  {
    date: '08/26/25',
    type: 'MODEL',
    title: 'Hermes‑4‑14B',
    href: 'https://huggingface.co/collections/NousResearch/hermes-4-collection-68a731bfd452e20816725728',
    description: 'Small and dense Hermes variant for local inference.',
  },
  {
    date: '08/14/25',
    type: 'RESEARCH',
    title: 'Measuring Thinking Efficiency in Reasoning Models',
    href: '/measuring-thinking-efficiency-in-reasoning-models-the-missing-benchmark/',
    description: 'Measuring Thinking Efficiency in Reasoning Models: The Missing Benchmark',
  },
  {
    date: '07/11/25',
    type: 'DATASET',
    title: 'Hermes 3 Dataset',
    href: 'https://huggingface.co/datasets/NousResearch/Hermes-3-Dataset',
    description: 'Complete dataset used in pretraining of Hermes 3 models',
  },
  {
    date: '05/29/25',
    type: 'RESEARCH',
    title: 'Steering the Shoggoth',
    href: '/steering-the-shoggoth-taming-llms-with-sequential-monte-carlo/',
    description: 'Taming LLMs with Sequential Monte Carlo',
  },
  {
    date: '05/14/25',
    type: 'TRAINING',
    title: 'Psyche Network',
    href: 'https://psyche.network/',
    description: 'Open infrastructure democratizing AI development',
  },
  {
    date: '04/29/25',
    type: 'FRAMEWORK',
    title: 'Atropos',
    href: 'https://github.com/NousResearch/atropos',
    description: 'Language Model RL Environments',
  },
  {
    date: '02/14/25',
    type: 'MODEL',
    title: 'DeepHermes-3-Llama-3-8B-Preview',
    href: 'https://huggingface.co/NousResearch/DeepHermes-3-Llama-3-8B-Preview',
    description: 'Model with deep reasoning and chat modes',
  },
  {
    date: '12/11/24',
    type: 'MODEL',
    title: 'Hermes-3-Llama-3.2-3B',
    href: 'https://huggingface.co/NousResearch/Hermes-3-Llama-3.2-3B',
    description: 'Model that can run on most modern hardware',
  },
  {
    date: '11/29/24',
    type: 'SIMULATOR',
    title: 'GOD',
    href: 'https://x.com/god',
    description: 'Social agent',
  },
  {
    date: '11/29/24',
    type: 'SIMULATOR',
    title: 'S8N',
    href: 'https://x.com/s8n',
    description: 'Social agent',
  },
  {
    date: '11/29/24',
    type: 'PAPER',
    title: 'DeMo: Decoupled Momentum Optimization',
    href: 'https://arxiv.org/pdf/2411.19870',
    description: 'Technical report',
  },
  {
    date: '11/08/24',
    type: 'SIMULATOR',
    title: 'Hermes Chat',
    href: 'https://hermes.nousresearch.com/',
    description: 'Chat Interface',
  },
  {
    date: '10/29/24',
    type: 'SIMULATOR',
    title: 'TEE',
    href: 'https://x.com/tee_hee_he',
    description: 'Autonomous agent',
  },
  {
    date: '08/26/24',
    type: 'PAPER',
    title: 'A Preliminary Report On DisTrO',
    href: 'https://github.com/NousResearch/DisTrO/blob/main/A_Preliminary_Report_on_DisTrO.pdf',
    description: 'Technical report',
  },
  {
    date: '08/24/24',
    type: 'MODEL',
    title: 'Hermes 3 405B',
    href: 'https://huggingface.co/NousResearch/Hermes-3-Llama-3.1-405B',
    description: 'Model',
  },
  {
    date: '08/14/24',
    type: 'PAPER',
    title: 'Hermes 3 Technical Report',
    href: '/wp-content/uploads/2024/08/Hermes-3-Technical-Report.pdf',
    description: 'Technical report',
  },
  {
    date: '06/27/24',
    type: 'MODEL',
    title: 'Hermes 2 Pro 70B',
    href: 'https://huggingface.co/NousResearch/Hermes-2-Pro-Llama-3-70B',
    description: 'Function-calling model',
  },
  {
    date: '06/20/24',
    type: 'MODEL',
    title: 'Hermes 2 Theta',
    href: 'https://huggingface.co/NousResearch/Hermes-2-Theta-Llama-3-70B-GGUF',
    description: 'Model',
  },
  {
    date: '06/11/24',
    type: 'DATASET',
    title: 'Character Codex',
    href: 'https://huggingface.co/datasets/NousResearch/CharacterCodex',
    description: 'Roleplaying dataset',
  },
  {
    date: '03/23/24',
    type: 'CODE',
    title: 'Nous WorldSim',
    href: 'https://worldsim.nousresearch.com/',
    description: 'CLI simulator',
  },
  {
    date: '03/15/24',
    type: 'PROMPT',
    title: 'Original Nous WorldSim Prompt',
    href: 'https://x.com/karan4d/status/1768836844207378463',
    description: 'Prompt engineering',
  },
  {
    date: '03/11/24',
    type: 'MODEL',
    title: 'Hermes-2-Pro-Mistral-7B',
    href: 'https://huggingface.co/NousResearch/Hermes-2-Pro-Mistral-7B',
    description: 'Master function-calling model',
  },
  {
    date: '03/07/24',
    type: 'MODEL',
    title: 'NousResearch/Genstruct-7B',
    href: 'https://huggingface.co/NousResearch/Genstruct-7B',
    description: 'Data synthesis model',
  },
  {
    date: '03/05/24',
    type: 'PAPER',
    title: 'Nous Research Official Branding Booklet',
    href: '/wp-content/uploads/2024/03/NOUS-BRAND-BOOKLET-firstedition_1.pdf',
    description: 'Design & story of Nous',
  },
  {
    date: '02/20/24',
    type: 'MODEL',
    title: 'NousResearch/Nous-Hermes-2-Mistral-7B-DPO',
    href: 'https://huggingface.co/NousResearch/Nous-Hermes-2-Mistral-7B-DPO',
    description: '7B model',
  },
  {
    date: '01/29/24',
    type: 'SUBNET',
    title: 'NousResearch/finetuning-subnet',
    href: 'https://github.com/NousResearch/finetuning-subnet',
    description: 'Evals on-chain',
  },
  {
    date: '01/15/24',
    type: 'MODEL',
    title: 'NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO',
    href: 'https://huggingface.co/NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO',
    description: 'MoE model + DPO',
  },
  {
    date: '01/15/24',
    type: 'MODEL',
    title: 'NousResearch/Nous-Hermes-2-Mixtral-8x7B-SFT',
    href: 'https://huggingface.co/NousResearch/Nous-Hermes-2-Mixtral-8x7B-SFT',
    description: 'MoE model - DPO',
  },
  {
    date: '01/15/24',
    type: 'MODEL',
    title: 'NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO-GGUF',
    href: 'https://huggingface.co/NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO-GGUF',
    description: 'Quantized MoE model',
  },
  {
    date: '12/25/23',
    type: 'MODEL',
    title: 'NousResearch/Nous-Hermes-2-Yi-34B',
    href: 'https://huggingface.co/NousResearch/Nous-Hermes-2-Yi-34B',
    description: 'Hermes on Yi',
  },
  {
    date: '11/14/23',
    type: 'MODEL',
    title: 'NousResearch/Nous-Capybara-34B',
    href: 'https://huggingface.co/NousResearch/Nous-Capybara-34B',
    description: 'Capybara-series model',
  },
  {
    date: '11/02/23',
    type: 'MODEL',
    title: 'NousResearch/Yarn-Mistral-7b-128k',
    href: 'https://huggingface.co/NousResearch/Yarn-Mistral-7b-128k',
    description: 'Long-context model',
  },
  {
    date: '10/30/23',
    type: 'MODEL',
    title: 'NousResearch/Obsidian-3B-V0.5',
    href: 'https://huggingface.co/NousResearch/Obsidian-3B-V0.5',
    description: 'Multimodal vision LLM',
  },
  {
    date: '10/30/23',
    type: 'CODE',
    title: 'NousResearch/Obsidian',
    href: 'https://github.com/NousResearch/Obsidian',
    description: 'Code for obsidian model',
  },
  {
    date: '08/31/23',
    type: 'PAPER',
    title: 'YaRN: Efficient Context Window Extension of Large Language Models',
    href: 'https://arxiv.org/abs/2309.00071',
    description: 'Architecture behind YaRN models',
  },
  {
    date: '07/21/23',
    type: 'MODEL',
    title: 'NousResearch/Nous-Hermes-Llama2-13b',
    href: 'https://huggingface.co/NousResearch/Nous-Hermes-Llama2-13b',
    description: 'Hermes on Llama2',
  },
];
